### ISSUE TITLE
binary installation error with piper

### ISSUE THREAD

**Issue by yuanzhou** [DeepPhe/DeepPhe-Release#11]
Successfully compiled the binary zip in `deepphe-distribution`. When testing in the unzipped binary directory, `sh startNlpGui.sh` brought up the Piper with this popup error:

![capture](https://user-images.githubusercontent.com/195873/47733599-f9b0d980-dc3e-11e8-8e29-2b869767d8e9.PNG)

Here is the console output:

````
[zhy19@localhost bin]$ sh startNlpGui.sh
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [ProgressAppender] additivity to [false].
log4j: Level value for ProgressAppender is  [INFO].
log4j: ProgressAppender level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%m].
log4j: Adding appender named [noEolAppender] to category [ProgressAppender].
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [ProgressDone] additivity to [false].
log4j: Level value for ProgressDone is  [INFO].
log4j: ProgressDone level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%m%n].
log4j: Adding appender named [eolAppender] to category [ProgressDone].
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{dd MMM yyyy HH:mm:ss} %5p %c{1} - %m%n].
log4j: Adding appender named [consoleAppender] to category [root].
30 Oct 2018 12:22:53  INFO PiperRunnerGui - 1. Load a Piper File.
30 Oct 2018 12:22:53  INFO PiperRunnerGui -    Once selected, the right panel will be display the piper file text.
30 Oct 2018 12:22:53  INFO PiperRunnerGui - 2. Edit Command Line Interface (cli) values for Pipe Bit Parameters.
30 Oct 2018 12:22:53  INFO PiperRunnerGui -    Parameters and values are displayed in the left table.
30 Oct 2018 12:22:53  INFO PiperRunnerGui -    Values can be edited directly on the table.
30 Oct 2018 12:22:53  INFO PiperRunnerGui -    In the rightmost column is a button to open a Filechooser if needed.
30 Oct 2018 12:22:53  INFO PiperRunnerGui - 3. Alternatively, load a previously saved piper_cli parameter file.
30 Oct 2018 12:22:53  INFO PiperRunnerGui - 4. Save your Command Line Interface (cli) values to a piper_cli parameter file.
30 Oct 2018 12:22:53  INFO PiperRunnerGui - 5. Run the Pipeline.
30 Oct 2018 12:22:53  INFO PiperRunnerPanel - Loading Piper File: org/apache/ctakes/cancer/pipeline/DeepPhe.piper
30 Oct 2018 12:22:53 ERROR PiperFileReader - No piper file found for org/apache/ctakes/cancer/pipeline/DeepPhe.piper
30 Oct 2018 12:22:53 ERROR PiperRunnerPanel - No piper file found for org/apache/ctakes/cancer/pipeline/DeepPhe.piper
````

**Comment by seanfinan** [comment]
I cannot duplicate this problem.  The message is indicating a path that existed in a previous version.  Is it possible that you have an old copy of DeepPhe in your path?

**Comment by yuanzhou** [comment]
I compiled the release code again in a clean directory. Followed the instructions here: https://github.com/DeepPhe/DeepPhe-Release/wiki/Quick-Start#building-the-binary-installation

And reproduced the same popup error. I don't know why the instructions mentions "deepphe-viz-neo4j/target" in point 1.

What is the purpose of building and using this binary package? it still requires to build in command line, and the script brings up the Piper GUI as well.

**Comment by seanfinan** [comment]
Updated the path to the piper - it was an old path.

The instructions mention deepphe-viz-neo4j/target" in point 1 because the neo4j plugin is built at the same time as the system.   It is referenced again later in the View data with DeepPhe Viz section.  I have added links and relabled for additional clarity.

The purpose of building the binary is so that users can more easily distribute the application to other machines that do not have the necessary developer environment (maven, jdk).

**Comment by yuanzhou** [comment]
Pulled the fix and re-tested on my Linux, the error message popup is gone. While I was running the pipeline, I noticed this error and the program stopped there.

![capture](https://user-images.githubusercontent.com/195873/47804555-7a3d0c00-dd0b-11e8-925b-8dc20e4bb656.PNG)

**Comment by seanfinan** [comment]
Can you check that cTAKES.error.log file and send a snippet?  Thanks

**Comment by yuanzhou** [comment]
````
org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.cancer.ae.DocEpisodeTagger" failed.  (Descriptor: <unknown>)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:271)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:170)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:448)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:139)
	at org.apache.ctakes.core.pipeline.PipelineBuilder.run(PipelineBuilder.java:398)
	at org.apache.ctakes.core.pipeline.PiperFileRunner.run(PiperFileRunner.java:82)
	at org.apache.ctakes.gui.pipeline.PiperRunnerPanel$PiperFileRunnable.run(PiperRunnerPanel.java:545)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Please specify PARAM_IS_TRAINING - unable to infer it from context
	at org.cleartk.ml.CleartkAnnotator.initialize(CleartkAnnotator.java:109)
	at org.apache.ctakes.cancer.ae.DocEpisodeTagger.initialize(DocEpisodeTagger.java:84)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:266)
	... 29 more
````

**Comment by seanfinan** [comment]
Press enter after typing "Breast", otherwise it hasn't been set.  deepphe ran without a domain set.

**Comment by yuanzhou** [comment]
Got it work this time by pressing the enter button. In the regular GUI build, "Breast" is populated by default.
