### ISSUE TITLE
Troubleshooting failures - provide name of the document that caused failure?

### ISSUE THREAD

**Issue by fedorov** [DeepPhe/DeepPhe-Release#25]
While running the pipeline, it stopped with the following

```
Loading configuration.
Loading feature templates.
Loading lexica.
Loading model:
........................................................................................
03 Jan 2019 11:58:11  INFO ClearNLPDependencyParserAE - Finished initializing
03 Jan 2019 11:58:11  INFO Coreferences - Starting initializing
03 Jan 2019 11:58:14  INFO Coreferences - Finished initializing
03 Jan 2019 11:58:14 ERROR PiperFileRunner - Initialization of annotator class "org.healthnlp.deepphe.uima.ae.PatientSummarizer" failed.  (Descriptor: <unknown>)
03 Jan 2019 11:58:14  INFO PiperFileRunner - For more information please see log file /Users/fedorov/github/DeepPhe-Release/cTAKES.error.log
```

The log file has this:

```
org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.healthnlp.deepphe.uima.ae.PatientSummarizer" failed.  (Descriptor: <unknown>)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:271)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:170)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:448)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:139)
	at org.apache.ctakes.core.pipeline.PipelineBuilder.run(PipelineBuilder.java:398)
	at org.apache.ctakes.core.pipeline.PiperFileRunner.run(PiperFileRunner.java:82)
	at org.apache.ctakes.gui.pipeline.PiperRunnerPanel$PiperFileRunnable.run(PiperRunnerPanel.java:545)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: PatientSummarizer already Registered!  To add an engine twice, please use the parameter EngineName to specify unique names OR if you are developing the engine override getEngineName() method.
	at org.apache.ctakes.core.patient.PatientNoteStore.registerEngine(PatientNoteStore.java:69)
	at org.apache.ctakes.core.patient.AbstractPatientConsumer.initialize(AbstractPatientConsumer.java:76)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:266)
	... 29 more
```

I don't know if that is helpful to the developers (I hope so), but to me, as a user, it would be more helpful to know what input file caused the error, so I could review that report and exclude from the analysis potentially. Does it make sense to add such document information to the log?

**Comment by seanfinan** [comment]
Hi Andrey,
This is a known problem in 3rd-party software.   
https://github.com/DeepPhe/DeepPhe-Release/issues/19

**Comment by fedorov** [comment]
Indeed, after restarting the GUI, it seems it's been running for longer time without crash.

**Comment by fedorov** [comment]
@seanfinan I suggest you add a note to the documentation saying that GUI can only be used to run the pipeline once without restarting. Or perhaps the GUI should close automatically once the pipeline is finished, until the 3rd-party software is fixed.

**Comment by seanfinan** [comment]
@fedorov Good ideas.  I have added a note in the documentation.
